### ISSUE TITLE
New card images lower quality?

### ISSUE THREAD

**Issue by weeco** [starfirehq/starfire-assets#4]
The new images don't have the elixir icon + elixir count. Also they appear to be (even though slightly) lossy compressed.

https://github.com/starfirehq/starfire-assets/blob/master/cards/hunter.png
vs
https://github.com/starfirehq/starfire-assets/blob/master/cards/arrows.png

Do you intend to fix the new card images?

Btw: I saw that you've added the new card images very quickly, thanks for that!

**Comment by austinhallock** [comment]
Yeah, those were placeholder so I could add [this](https://starfire.games/clash-royale/mod/new-cards) right after the update landed. I just updated with the actual frames
